[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock
[authorization]
trusted_clients:
    192.168.4.215
    127.0.0.1
    192.168.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]


#[power Printer]
#type: tplink_smartplug
#address: 192.168.4.147
#output_id: 0  # First outlet on same plug
#on_when_job_queued: true
#locked_while_printing: true
#restart_klipper_when_powered: false
#off_when_shutdown: false

#[power Lights]
#type: tplink_smartplug
#address: 192.168.4.147
#output_id: 1  # Second outlet on same plug
#initial_state: on
#off_when_shutdown: false

[file_manager]
enable_object_processing: True
queue_gcode_uploads: True

[history]

[update_manager]
channel: stable
refresh_interval: 168
enable_auto_refresh: True

[update_manager mainsail]
path: /home/pi/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen

[update_manager mobileraker]
install_script: /home/pi/mobileraker_companion/scripts/install.sh
requirements: /home/pi/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/pi/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/pi/mobileraker_companion
type: git_repo

# Sonar update_manager entry
[update_manager sonar]
type: git_repo
path: ~/sonar
origin: https://github.com/mainsail-crew/sonar.git
primary_branch: main
managed_services: sonar
system_dependencies: resources/system-dependencies.json

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main